# Below code is image of Backend and goes to server folder
FROM node:alpine
WORKDIR /app
COPY . .
EXPOSE 8081
CMD node server.js

# Below code is image of Frontend
# FROM node:alpine
# WORKDIR /app
# COPY . .
# EXPOSE 8080
# CMD npm start